/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * FIT AI API
 * RESTful API for AI-powered workout planning with chatbot integration.
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch"
export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay]

export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minLength 1 */
  name: string
  /** @minimum 0 */
  order: number
  /** @minimum 1 */
  sets: number
  /** @minimum 1 */
  reps: number
  /** @minimum 1 */
  restTimeInSeconds: number
}

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay
  isRest?: boolean
  /** @minimum 1 */
  estimatedDurationInSeconds: number
  coverImageUrl?: string
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[]
}

export type CreateWorkoutPlanBody = {
  /** @minLength 1 */
  name: string
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[]
}

export type CreateWorkoutPlan201WorkoutPlanWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlan201WorkoutPlanWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutPlanWorkoutDaysItemWeekDay]

export const CreateWorkoutPlan201WorkoutPlanWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const

export type CreateWorkoutPlan201WorkoutPlanWorkoutDaysItemExercisesItem = {
  /** @minLength 1 */
  name: string
  /** @minimum 0 */
  order: number
  /** @minimum 1 */
  sets: number
  /** @minimum 1 */
  reps: number
  /** @minimum 1 */
  restTimeInSeconds: number
}

export type CreateWorkoutPlan201WorkoutPlanWorkoutDaysItem = {
  /** @minLength 1 */
  name: string
  weekDay: CreateWorkoutPlan201WorkoutPlanWorkoutDaysItemWeekDay
  isRest: boolean
  /** @minimum 1 */
  estimatedDurationInSeconds: number
  coverImageUrl?: string
  exercises: CreateWorkoutPlan201WorkoutPlanWorkoutDaysItemExercisesItem[]
}

export type CreateWorkoutPlan201WorkoutPlan = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  /** @minLength 1 */
  name: string
  workoutDays: CreateWorkoutPlan201WorkoutPlanWorkoutDaysItem[]
}

export type CreateWorkoutPlan201 = {
  workoutPlan: CreateWorkoutPlan201WorkoutPlan
}

export type CreateWorkoutPlan400 = {
  message: string
  code: string
}

export type CreateWorkoutPlan401 = {
  message: string
  code: string
}

export type CreateWorkoutPlan500 = {
  message: string
  code: string
}

export type FetchWorkoutPlanParams = {
  isActive?: FetchWorkoutPlanIsActive
}

export type FetchWorkoutPlanIsActive =
  (typeof FetchWorkoutPlanIsActive)[keyof typeof FetchWorkoutPlanIsActive]

export const FetchWorkoutPlanIsActive = {
  true: "true",
  false: "false",
} as const

export type FetchWorkoutPlan200WorkoutPlansItemWorkoutDaysItemWeekDay =
  (typeof FetchWorkoutPlan200WorkoutPlansItemWorkoutDaysItemWeekDay)[keyof typeof FetchWorkoutPlan200WorkoutPlansItemWorkoutDaysItemWeekDay]

export const FetchWorkoutPlan200WorkoutPlansItemWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const

export type FetchWorkoutPlan200WorkoutPlansItemWorkoutDaysItemExercisesItem = {
  /** @minLength 1 */
  name: string
  /** @minimum 0 */
  order: number
  /** @minimum 1 */
  sets: number
  /** @minimum 1 */
  reps: number
  /** @minimum 1 */
  restTimeInSeconds: number
}

export type FetchWorkoutPlan200WorkoutPlansItemWorkoutDaysItem = {
  /** @minLength 1 */
  name: string
  weekDay: FetchWorkoutPlan200WorkoutPlansItemWorkoutDaysItemWeekDay
  isRest: boolean
  /** @minimum 1 */
  estimatedDurationInSeconds: number
  coverImageUrl?: string
  exercises: FetchWorkoutPlan200WorkoutPlansItemWorkoutDaysItemExercisesItem[]
}

export type FetchWorkoutPlan200WorkoutPlansItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  /** @minLength 1 */
  name: string
  workoutDays: FetchWorkoutPlan200WorkoutPlansItemWorkoutDaysItem[]
}

export type FetchWorkoutPlan200 = {
  workoutPlans: FetchWorkoutPlan200WorkoutPlansItem[]
}

export type FetchWorkoutPlan400 = {
  message: string
  code: string
}

export type FetchWorkoutPlan401 = {
  message: string
  code: string
}

export type FetchWorkoutPlan500 = {
  message: string
  code: string
}

export type GetWorkoutPlan200WorkoutPlanWorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlan200WorkoutPlanWorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlan200WorkoutPlanWorkoutDaysItemWeekDay]

export const GetWorkoutPlan200WorkoutPlanWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const

export type GetWorkoutPlan200WorkoutPlanWorkoutDaysItemExercisesItem = {
  /** @minLength 1 */
  name: string
  /** @minimum 0 */
  order: number
  /** @minimum 1 */
  sets: number
  /** @minimum 1 */
  reps: number
  /** @minimum 1 */
  restTimeInSeconds: number
}

export type GetWorkoutPlan200WorkoutPlanWorkoutDaysItem = {
  /** @minLength 1 */
  name: string
  weekDay: GetWorkoutPlan200WorkoutPlanWorkoutDaysItemWeekDay
  isRest: boolean
  /** @minimum 1 */
  estimatedDurationInSeconds: number
  coverImageUrl?: string
  exercises: GetWorkoutPlan200WorkoutPlanWorkoutDaysItemExercisesItem[]
}

export type GetWorkoutPlan200WorkoutPlan = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  /** @minLength 1 */
  name: string
  workoutDays: GetWorkoutPlan200WorkoutPlanWorkoutDaysItem[]
}

export type GetWorkoutPlan200 = {
  workoutPlan: GetWorkoutPlan200WorkoutPlan
}

export type GetWorkoutPlan400 = {
  message: string
  code: string
}

export type GetWorkoutPlan401 = {
  message: string
  code: string
}

export type GetWorkoutPlan404 = {
  message: string
  code: string
}

export type GetWorkoutPlan500 = {
  message: string
  code: string
}

export type GetWorkoutDay200WorkoutDayWeekDay =
  (typeof GetWorkoutDay200WorkoutDayWeekDay)[keyof typeof GetWorkoutDay200WorkoutDayWeekDay]

export const GetWorkoutDay200WorkoutDayWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const

export type GetWorkoutDay200WorkoutDayExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  name: string
  order: number
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string
  sets: number
  reps: number
  restTimeInSeconds: number
}

export type GetWorkoutDay200WorkoutDaySessionsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  startedAt?: string
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$ */
  completedAt?: string
}

export type GetWorkoutDay200WorkoutDay = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  name: string
  isRest: boolean
  coverImageUrl?: string
  estimatedDurationInSeconds: number
  weekDay: GetWorkoutDay200WorkoutDayWeekDay
  exercises: GetWorkoutDay200WorkoutDayExercisesItem[]
  sessions: GetWorkoutDay200WorkoutDaySessionsItem[]
}

export type GetWorkoutDay200 = {
  workoutDay: GetWorkoutDay200WorkoutDay
}

export type GetWorkoutDay400 = {
  message: string
  code: string
}

export type GetWorkoutDay401 = {
  message: string
  code: string
}

export type GetWorkoutDay404 = {
  message: string
  code: string
}

export type GetWorkoutDay500 = {
  message: string
  code: string
}

export type GetWorkoutPlanStatsParams = {
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  from: string
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  to: string
}

export type GetWorkoutPlanStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayStarted: boolean
    workoutDayCompleted: boolean
  }
}

export type GetWorkoutPlanStats200 = {
  workoutStreak: number
  consistencyByDay: GetWorkoutPlanStats200ConsistencyByDay
  completedWorkoutsCount: number
  conclusionRate: number
  totalTimeInSeconds: number
}

export type GetWorkoutPlanStats400 = {
  message: string
  code: string
}

export type GetWorkoutPlanStats401 = {
  message: string
  code: string
}

export type GetWorkoutPlanStats404 = {
  message: string
  code: string
}

export type GetWorkoutPlanStats422 = {
  message: string
  code: string
}

export type GetWorkoutPlanStats500 = {
  message: string
  code: string
}

export type StartWorkoutSessionBody = { [key: string]: unknown }

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userWorkoutSessionId: string
}

export type StartWorkoutSession400 = {
  message: string
  code: string
}

export type StartWorkoutSession401 = {
  message: string
  code: string
}

export type StartWorkoutSession404 = {
  message: string
  code: string
}

export type StartWorkoutSession409 = {
  message: string
  code: string
}

export type StartWorkoutSession422 = {
  message: string
  code: string
}

export type StartWorkoutSession500 = {
  message: string
  code: string
}

export type CompleteWorkoutSessionBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string
}

export type CompleteWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  startedAt: string
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$ */
  completedAt: string
}

export type CompleteWorkoutSession400 = {
  message: string
  code: string
}

export type CompleteWorkoutSession401 = {
  message: string
  code: string
}

export type CompleteWorkoutSession404 = {
  message: string
  code: string
}

export type CompleteWorkoutSession500 = {
  message: string
  code: string
}

export type GetUserProfile200User = {
  id: string
  name: string
  /** @nullable */
  age: number | null
  /** @nullable */
  weightInGrams: number | null
  /**
   * @minimum 0
   * @maximum 100
   * @nullable
   */
  bodyFatPercentage: number | null
  /** @nullable */
  heightInCentimeters: number | null
}

export type GetUserProfile200 = {
  user: GetUserProfile200User
}

export type GetUserProfile401 = {
  message: string
  code: string
}

export type GetUserProfile404 = {
  message: string
  code: string
}

export type GetUserProfile500 = {
  message: string
  code: string
}

export type UpdateUserTrainingMetricsBody = {
  /** @minimum 1 */
  weightInGrams: number
  /** @minimum 1 */
  heightInCentimeters: number
  /** @minimum 1 */
  age: number
  /**
   * @minimum 1
   * @maximum 100
   */
  bodyFatPercentage: number
}

export type UpdateUserTrainingMetrics200User = {
  id: string
  name: string
  /** @nullable */
  age: number | null
  /** @nullable */
  weightInGrams: number | null
  /**
   * @minimum 0
   * @maximum 100
   * @nullable
   */
  bodyFatPercentage: number | null
  /** @nullable */
  heightInCentimeters: number | null
}

export type UpdateUserTrainingMetrics200 = {
  user: UpdateUserTrainingMetrics200User
}

export type UpdateUserTrainingMetrics401 = {
  message: string
  code: string
}

export type UpdateUserTrainingMetrics404 = {
  message: string
  code: string
}

export type UpdateUserTrainingMetrics500 = {
  message: string
  code: string
}

export type GetHomeDataParams = {
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  date: string
}

export type GetHomeData200TodayWorkoutDayWeekDay =
  (typeof GetHomeData200TodayWorkoutDayWeekDay)[keyof typeof GetHomeData200TodayWorkoutDayWeekDay]

export const GetHomeData200TodayWorkoutDayWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const

export type GetHomeData200TodayWorkoutDay = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string
  name: string
  isRest: boolean
  weekDay: GetHomeData200TodayWorkoutDayWeekDay
  estimatedDurationInSeconds: number
  coverImageUrl?: string
  exercisesCount: number
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string
}

export type GetHomeData200ConsistencyByDay = {
  [key: string]: {
    workoutDayStarted: boolean
    workoutDayCompleted: boolean
  }
}

export type GetHomeData200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  activeWorkoutPlanId: string
  todayWorkoutDay: GetHomeData200TodayWorkoutDay
  workoutStreak: number
  consistencyByDay: GetHomeData200ConsistencyByDay
}

export type GetHomeData400 = {
  message: string
  code: string
}

export type GetHomeData401 = {
  message: string
  code: string
}

export type GetHomeData404 = {
  message: string
  code: string
}

export type GetHomeData500 = {
  message: string
  code: string
}

/**
 * @summary Create a workout plan
 */
export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlan201
  status: 201
}

export type createWorkoutPlanResponse400 = {
  data: CreateWorkoutPlan400
  status: 400
}

export type createWorkoutPlanResponse401 = {
  data: CreateWorkoutPlan401
  status: 401
}

export type createWorkoutPlanResponse500 = {
  data: CreateWorkoutPlan500
  status: 500
}

export type createWorkoutPlanResponseSuccess = createWorkoutPlanResponse201 & {
  headers: Headers
}
export type createWorkoutPlanResponseError = (
  | createWorkoutPlanResponse400
  | createWorkoutPlanResponse401
  | createWorkoutPlanResponse500
) & {
  headers: Headers
}

export type createWorkoutPlanResponse =
  | createWorkoutPlanResponseSuccess
  | createWorkoutPlanResponseError

export const getCreateWorkoutPlanUrl = () => {
  return `/workout-plans/`
}

export const createWorkoutPlan = async (
  createWorkoutPlanBody: CreateWorkoutPlanBody,
  options?: RequestInit
): Promise<createWorkoutPlanResponse> => {
  return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createWorkoutPlanBody),
  })
}

/**
 * @summary Fetch workout plans
 */
export type fetchWorkoutPlanResponse200 = {
  data: FetchWorkoutPlan200
  status: 200
}

export type fetchWorkoutPlanResponse400 = {
  data: FetchWorkoutPlan400
  status: 400
}

export type fetchWorkoutPlanResponse401 = {
  data: FetchWorkoutPlan401
  status: 401
}

export type fetchWorkoutPlanResponse500 = {
  data: FetchWorkoutPlan500
  status: 500
}

export type fetchWorkoutPlanResponseSuccess = fetchWorkoutPlanResponse200 & {
  headers: Headers
}
export type fetchWorkoutPlanResponseError = (
  | fetchWorkoutPlanResponse400
  | fetchWorkoutPlanResponse401
  | fetchWorkoutPlanResponse500
) & {
  headers: Headers
}

export type fetchWorkoutPlanResponse =
  | fetchWorkoutPlanResponseSuccess
  | fetchWorkoutPlanResponseError

export const getFetchWorkoutPlanUrl = (params?: FetchWorkoutPlanParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/workout-plans/?${stringifiedParams}`
    : `/workout-plans/`
}

export const fetchWorkoutPlan = async (
  params?: FetchWorkoutPlanParams,
  options?: RequestInit
): Promise<fetchWorkoutPlanResponse> => {
  return customFetch<fetchWorkoutPlanResponse>(getFetchWorkoutPlanUrl(params), {
    ...options,
    method: "GET",
  })
}

/**
 * @summary Get a workout plan
 */
export type getWorkoutPlanResponse200 = {
  data: GetWorkoutPlan200
  status: 200
}

export type getWorkoutPlanResponse400 = {
  data: GetWorkoutPlan400
  status: 400
}

export type getWorkoutPlanResponse401 = {
  data: GetWorkoutPlan401
  status: 401
}

export type getWorkoutPlanResponse404 = {
  data: GetWorkoutPlan404
  status: 404
}

export type getWorkoutPlanResponse500 = {
  data: GetWorkoutPlan500
  status: 500
}

export type getWorkoutPlanResponseSuccess = getWorkoutPlanResponse200 & {
  headers: Headers
}
export type getWorkoutPlanResponseError = (
  | getWorkoutPlanResponse400
  | getWorkoutPlanResponse401
  | getWorkoutPlanResponse404
  | getWorkoutPlanResponse500
) & {
  headers: Headers
}

export type getWorkoutPlanResponse =
  | getWorkoutPlanResponseSuccess
  | getWorkoutPlanResponseError

export const getGetWorkoutPlanUrl = (workoutPlanId: string) => {
  return `/workout-plans/${workoutPlanId}`
}

export const getWorkoutPlan = async (
  workoutPlanId: string,
  options?: RequestInit
): Promise<getWorkoutPlanResponse> => {
  return customFetch<getWorkoutPlanResponse>(
    getGetWorkoutPlanUrl(workoutPlanId),
    {
      ...options,
      method: "GET",
    }
  )
}

/**
 * @summary Get a workout day
 */
export type getWorkoutDayResponse200 = {
  data: GetWorkoutDay200
  status: 200
}

export type getWorkoutDayResponse400 = {
  data: GetWorkoutDay400
  status: 400
}

export type getWorkoutDayResponse401 = {
  data: GetWorkoutDay401
  status: 401
}

export type getWorkoutDayResponse404 = {
  data: GetWorkoutDay404
  status: 404
}

export type getWorkoutDayResponse500 = {
  data: GetWorkoutDay500
  status: 500
}

export type getWorkoutDayResponseSuccess = getWorkoutDayResponse200 & {
  headers: Headers
}
export type getWorkoutDayResponseError = (
  | getWorkoutDayResponse400
  | getWorkoutDayResponse401
  | getWorkoutDayResponse404
  | getWorkoutDayResponse500
) & {
  headers: Headers
}

export type getWorkoutDayResponse =
  | getWorkoutDayResponseSuccess
  | getWorkoutDayResponseError

export const getGetWorkoutDayUrl = (
  workoutPlanId: string,
  workoutDayId: string
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}`
}

export const getWorkoutDay = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit
): Promise<getWorkoutDayResponse> => {
  return customFetch<getWorkoutDayResponse>(
    getGetWorkoutDayUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "GET",
    }
  )
}

/**
 * @summary Get workout plan stats
 */
export type getWorkoutPlanStatsResponse200 = {
  data: GetWorkoutPlanStats200
  status: 200
}

export type getWorkoutPlanStatsResponse400 = {
  data: GetWorkoutPlanStats400
  status: 400
}

export type getWorkoutPlanStatsResponse401 = {
  data: GetWorkoutPlanStats401
  status: 401
}

export type getWorkoutPlanStatsResponse404 = {
  data: GetWorkoutPlanStats404
  status: 404
}

export type getWorkoutPlanStatsResponse422 = {
  data: GetWorkoutPlanStats422
  status: 422
}

export type getWorkoutPlanStatsResponse500 = {
  data: GetWorkoutPlanStats500
  status: 500
}

export type getWorkoutPlanStatsResponseSuccess =
  getWorkoutPlanStatsResponse200 & {
    headers: Headers
  }
export type getWorkoutPlanStatsResponseError = (
  | getWorkoutPlanStatsResponse400
  | getWorkoutPlanStatsResponse401
  | getWorkoutPlanStatsResponse404
  | getWorkoutPlanStatsResponse422
  | getWorkoutPlanStatsResponse500
) & {
  headers: Headers
}

export type getWorkoutPlanStatsResponse =
  | getWorkoutPlanStatsResponseSuccess
  | getWorkoutPlanStatsResponseError

export const getGetWorkoutPlanStatsUrl = (
  workoutPlanId: string,
  params: GetWorkoutPlanStatsParams
) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0
    ? `/workout-plans/${workoutPlanId}/stats?${stringifiedParams}`
    : `/workout-plans/${workoutPlanId}/stats`
}

export const getWorkoutPlanStats = async (
  workoutPlanId: string,
  params: GetWorkoutPlanStatsParams,
  options?: RequestInit
): Promise<getWorkoutPlanStatsResponse> => {
  return customFetch<getWorkoutPlanStatsResponse>(
    getGetWorkoutPlanStatsUrl(workoutPlanId, params),
    {
      ...options,
      method: "GET",
    }
  )
}

/**
 * @summary Start a workout session
 */
export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSession201
  status: 201
}

export type startWorkoutSessionResponse400 = {
  data: StartWorkoutSession400
  status: 400
}

export type startWorkoutSessionResponse401 = {
  data: StartWorkoutSession401
  status: 401
}

export type startWorkoutSessionResponse404 = {
  data: StartWorkoutSession404
  status: 404
}

export type startWorkoutSessionResponse409 = {
  data: StartWorkoutSession409
  status: 409
}

export type startWorkoutSessionResponse422 = {
  data: StartWorkoutSession422
  status: 422
}

export type startWorkoutSessionResponse500 = {
  data: StartWorkoutSession500
  status: 500
}

export type startWorkoutSessionResponseSuccess =
  startWorkoutSessionResponse201 & {
    headers: Headers
  }
export type startWorkoutSessionResponseError = (
  | startWorkoutSessionResponse400
  | startWorkoutSessionResponse401
  | startWorkoutSessionResponse404
  | startWorkoutSessionResponse409
  | startWorkoutSessionResponse422
  | startWorkoutSessionResponse500
) & {
  headers: Headers
}

export type startWorkoutSessionResponse =
  | startWorkoutSessionResponseSuccess
  | startWorkoutSessionResponseError

export const getStartWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`
}

export const startWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  startWorkoutSessionBody: StartWorkoutSessionBody,
  options?: RequestInit
): Promise<startWorkoutSessionResponse> => {
  return customFetch<startWorkoutSessionResponse>(
    getStartWorkoutSessionUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(startWorkoutSessionBody),
    }
  )
}

/**
 * @summary Complete a workout session
 */
export type completeWorkoutSessionResponse200 = {
  data: CompleteWorkoutSession200
  status: 200
}

export type completeWorkoutSessionResponse400 = {
  data: CompleteWorkoutSession400
  status: 400
}

export type completeWorkoutSessionResponse401 = {
  data: CompleteWorkoutSession401
  status: 401
}

export type completeWorkoutSessionResponse404 = {
  data: CompleteWorkoutSession404
  status: 404
}

export type completeWorkoutSessionResponse500 = {
  data: CompleteWorkoutSession500
  status: 500
}

export type completeWorkoutSessionResponseSuccess =
  completeWorkoutSessionResponse200 & {
    headers: Headers
  }
export type completeWorkoutSessionResponseError = (
  | completeWorkoutSessionResponse400
  | completeWorkoutSessionResponse401
  | completeWorkoutSessionResponse404
  | completeWorkoutSessionResponse500
) & {
  headers: Headers
}

export type completeWorkoutSessionResponse =
  | completeWorkoutSessionResponseSuccess
  | completeWorkoutSessionResponseError

export const getCompleteWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  workoutSessionId: string
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${workoutSessionId}`
}

export const completeWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  workoutSessionId: string,
  completeWorkoutSessionBody: CompleteWorkoutSessionBody,
  options?: RequestInit
): Promise<completeWorkoutSessionResponse> => {
  return customFetch<completeWorkoutSessionResponse>(
    getCompleteWorkoutSessionUrl(workoutPlanId, workoutDayId, workoutSessionId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(completeWorkoutSessionBody),
    }
  )
}

/**
 * @summary Get user profile
 */
export type getUserProfileResponse200 = {
  data: GetUserProfile200
  status: 200
}

export type getUserProfileResponse401 = {
  data: GetUserProfile401
  status: 401
}

export type getUserProfileResponse404 = {
  data: GetUserProfile404
  status: 404
}

export type getUserProfileResponse500 = {
  data: GetUserProfile500
  status: 500
}

export type getUserProfileResponseSuccess = getUserProfileResponse200 & {
  headers: Headers
}
export type getUserProfileResponseError = (
  | getUserProfileResponse401
  | getUserProfileResponse404
  | getUserProfileResponse500
) & {
  headers: Headers
}

export type getUserProfileResponse =
  | getUserProfileResponseSuccess
  | getUserProfileResponseError

export const getGetUserProfileUrl = () => {
  return `/users/me`
}

export const getUserProfile = async (
  options?: RequestInit
): Promise<getUserProfileResponse> => {
  return customFetch<getUserProfileResponse>(getGetUserProfileUrl(), {
    ...options,
    method: "GET",
  })
}

/**
 * @summary Update user training metrics
 */
export type updateUserTrainingMetricsResponse200 = {
  data: UpdateUserTrainingMetrics200
  status: 200
}

export type updateUserTrainingMetricsResponse401 = {
  data: UpdateUserTrainingMetrics401
  status: 401
}

export type updateUserTrainingMetricsResponse404 = {
  data: UpdateUserTrainingMetrics404
  status: 404
}

export type updateUserTrainingMetricsResponse500 = {
  data: UpdateUserTrainingMetrics500
  status: 500
}

export type updateUserTrainingMetricsResponseSuccess =
  updateUserTrainingMetricsResponse200 & {
    headers: Headers
  }
export type updateUserTrainingMetricsResponseError = (
  | updateUserTrainingMetricsResponse401
  | updateUserTrainingMetricsResponse404
  | updateUserTrainingMetricsResponse500
) & {
  headers: Headers
}

export type updateUserTrainingMetricsResponse =
  | updateUserTrainingMetricsResponseSuccess
  | updateUserTrainingMetricsResponseError

export const getUpdateUserTrainingMetricsUrl = () => {
  return `/users/`
}

export const updateUserTrainingMetrics = async (
  updateUserTrainingMetricsBody: UpdateUserTrainingMetricsBody,
  options?: RequestInit
): Promise<updateUserTrainingMetricsResponse> => {
  return customFetch<updateUserTrainingMetricsResponse>(
    getUpdateUserTrainingMetricsUrl(),
    {
      ...options,
      method: "PUT",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateUserTrainingMetricsBody),
    }
  )
}

/**
 * @summary Get home data
 */
export type getHomeDataResponse200 = {
  data: GetHomeData200
  status: 200
}

export type getHomeDataResponse400 = {
  data: GetHomeData400
  status: 400
}

export type getHomeDataResponse401 = {
  data: GetHomeData401
  status: 401
}

export type getHomeDataResponse404 = {
  data: GetHomeData404
  status: 404
}

export type getHomeDataResponse500 = {
  data: GetHomeData500
  status: 500
}

export type getHomeDataResponseSuccess = getHomeDataResponse200 & {
  headers: Headers
}
export type getHomeDataResponseError = (
  | getHomeDataResponse400
  | getHomeDataResponse401
  | getHomeDataResponse404
  | getHomeDataResponse500
) & {
  headers: Headers
}

export type getHomeDataResponse =
  | getHomeDataResponseSuccess
  | getHomeDataResponseError

export const getGetHomeDataUrl = (params: GetHomeDataParams) => {
  const normalizedParams = new URLSearchParams()

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString())
    }
  })

  const stringifiedParams = normalizedParams.toString()

  return stringifiedParams.length > 0 ? `/home/?${stringifiedParams}` : `/home/`
}

export const getHomeData = async (
  params: GetHomeDataParams,
  options?: RequestInit
): Promise<getHomeDataResponse> => {
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(params), {
    ...options,
    method: "GET",
  })
}

/**
 * @summary Chat with AI personal trainer
 */
export type postAiResponse200 = {
  data: void
  status: 200
}

export type postAiResponseSuccess = postAiResponse200 & {
  headers: Headers
}
export type postAiResponse = postAiResponseSuccess

export const getPostAiUrl = () => {
  return `/ai/`
}

export const postAi = async (
  options?: RequestInit
): Promise<postAiResponse> => {
  return customFetch<postAiResponse>(getPostAiUrl(), {
    ...options,
    method: "POST",
  })
}
